
matrix:
  allow_failures:
    - name: lint
  include:
    - name: lint
      language: node_js
      node_js: stable
      script: npm run lint
    - name: 'test - stable'
      language: node_js
      node_js: stable
      script: npm test
      after_script: npx codecov
